Repository MirakuSan/infresCoinMarketCap, pull requests merged in 2021-09, with the labels that each got.

#13 Ajout du proxy dans le package.json du client pour changer le port
  api/package-lock.json
  client/package.json
  package-lock.json
Labels: bug

#23 Ajout du docker compose.
  docker-compose.yml
Labels: CI/CD

#34 Création de la méthode pour récup les infos globale du marché.
  api/index.js
Labels: enhancement, back

#36 Hotfix des requêtes /coin et /global pour ajouter le res.send oublié.
  .github/workflows/workflow-branches.yml
  .github/workflows/workflow-main.yml
  .github/workflows/workflow-release.yml
  api/index.js
  api/package-lock.json
Labels: bug, back

#44 [DOC] Ecriture du README
  README.md
Labels: documentation, enhancement
